<?php

/**
 * @file
 * Message integration with Schemes.
 */

include_once('asb_message.features.inc');

/**
 * Implements hook_og_membership_insert().
 */
function asb_message_og_membership_insert($og_membership) {
  if ($og_membership->state != OG_STATE_ACTIVE || $og_membership->entity_type != 'user') {
    // Membership isn't active.
    return;
  }

  if ($og_membership->group_type != 'node') {
    // For simplicity we operate only on membership with node groups.
    return;
  }

  if (!$og_membership->etid) {
    // Don't capture membership of anonymous user, that might be caused
    // when using Devel generate.
    return;
  }

  $node = node_load($og_membership->gid);
    // Create a "User joined" message.
  $message = message_create('scheme_membership', array('uid' => $og_membership->etid));

  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_node_groups_ref[] = $node;
  $wrapper->field_published->set($node->status);
  $wrapper->save();
}

/**
 * Implements hook_node_insert().
 */
function asb_message_node_insert($node) {
  list(,, $bundle) = entity_extract_ids('node', $node);
  if (!og_is_group_content_type('node', $bundle)) {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  if (!$wrapper->{'og_membership__' . OG_STATE_ACTIVE}->value()) {
    // Node isn't associate, or doesn't have an active association with
    // any group.
    return;
  }

  $nids = array();
  foreach ($wrapper->{'og_membership__' . OG_STATE_ACTIVE}->value() as $og_membership) {
    if ($og_membership->group_type != 'node') {
      // For simplicity we operate only on membership with node groups.
      continue;
    }
    $nids[] = $og_membership->gid;
  }

  if (!$nids) {
    return;
  }

  // Create a "Post in group" message. We don't use a token replacement
  // here as it needs to get the data from multiple values of the field.
  // Furthermore, this replacement probably doesn't make sense outside of
  // this message-type context, so we don't want to add another token,
  // that will not be used.
  $arguments['!groups'] = array(
    'callback' => 'asb_message_group_list',
    'pass message' => TRUE,
  );

  $facilitator = asb_message_get_facilitator($nids);
  $message = message_create('update_posted_in_scheme', array('arguments' => $arguments, 'uid' => $node->uid));
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_node_ref->set($node);
  $wrapper->field_node_groups_ref->set($nids);
  $wrapper->field_published->set($node->status);
  $wrapper->field_facilitator_ref->set($facilitator);
  // dsm($node);
  $wrapper->save();
}

/**
 * Message callback; Show a comma separated list of groups.
 *
 * @param $message
 *   The message entity.
 */
function asb_message_group_list(Message $message) {
  $wrapper = entity_metadata_wrapper('message', $message);
  $items = array();
  foreach ($wrapper->field_node_groups_ref->value() as $node) {
    if (!node_access('view', $node)) {
      // User doesn't have access to view the group.
      continue;
    }
    $url = entity_uri('node', $node);
    $label = entity_label('node', $node);
    $items[] = l($label, $url['path'], $url['options']);
  }
  return implode(', ', $items);
}

function asb_message_get_facilitator($nids) {
  foreach ($nids as $key => $value) {
    $node = node_load($value);
    if(isset($node->field_facilitator['und'][0]['target_id'])) {
      $facilitator = $node->field_facilitator['und'][0]['target_id'];
      return $facilitator;
    }
  }
}

/**
 * Implements hook_block_info()
 *
 * Create a private message block
 */
function asb_message_block_info() {
  // This example comes from node.module.
  $blocks['pmessages'] = array(
    'info' => t('Private Messages'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function asb_message_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'pmessages':
      $block['subject'] = t('Messages');
      $block['content'] = asb_message_get_pms();
      break;
  }
  return $block;
}

function asb_message_get_pms() {
  global $user;
// Generate the query to load the messages.
// Replace 'inbox' with 'sent' to display sent messages or 'list' to display all messages.
  $query = _privatemsg_assemble_query('list', $user, 'inbox');
// Load 5 messages/threads. Replace 5 if you want to display a different amount of messages.
  $list = array();
  $tb = array();
  $count=0;
  foreach ($query->execute() as $thread) {
    if ($count <=5) {
      $table_parts = array();
      // Generate a link with the subject as title that points to the view message page.
      // $list[] = l($thread->subject, 'messages/view/'. $thread->thread_id);
      // take a look at $thread to see if what you needed is already there, so you can bypass other theming functions (you probably shouldnt)
      // proper solution:
      $theme_variables=array('thread' => (array)$thread);
      $subject=theme('privatemsg_list_field__subject', $theme_variables);
      $list_parts[]=$subject['data'];
      $list_parts[]=t('from');
      $participants=theme('privatemsg_list_field__participants', $theme_variables);
      $list_parts[]=$participants['data'];
      $last_updated=theme('privatemsg_list_field__last_updated', $theme_variables);
      $list_parts[]=$last_updated['data'];

      $table_parts['subject']=$subject['data'];
      $table_parts['from']=$participants['data'];
      $last_updated=theme('privatemsg_list_field__last_updated', $theme_variables);
      $table_parts['sent']=$last_updated['data'];
      $table_parts['reply'] = '<a class="pm-reply" href="/messages/view/' .$thread->thread_id .'" target="_blank">reply</a>';
      $tb[] = array($table_parts['from'],$table_parts['subject'],$table_parts['sent'],$table_parts['reply']);
      $list[] = implode(' ',$list_parts);
      $count++;
    } else {
      break;
    }
  }
// Display list as a themed item_list.
  $header = array(
    'from' => array('data' => t('From')),
    'subject' => array('data' => t('Subject')),
    'date' => array('data' => t('Date')),
  );
  return theme('table', array('header' => $header, 'rows' => $tb, 'attributes' => array( 'class' => array('pmessages'))));
}

function asb_message_form_privatemsg_new_alter(&$form, &$form_state) {
  // Check if a default value is configured for the to field.
  if (!empty($form['recipient']['#default_value'])) {
    global $user;
    // Display a visible markup element.
    $form['recipient_display'] = array(
      '#value' => t('To: @recipients', array('@recipients' => $form['recipient']['#default_value'])),
      '#weight' => -10,
    );
    // Get the type of message from the url string
    $url_vals = asb_message_privatemsg_check_url();
    if (!isset($form['thread_id'])) {
      $recipients_plain = str_replace('[user]', '', $form['recipient']['#default_value']);
      // Here we set the title for skills donations
      if(!empty($url_vals['type'])) {
        // Add the custom validation handler to add scheme link
        $form['#validate'][] = 'asb_message_add_scheme_link_validate';
        if($url_vals['type'] == 'facilitator') {
          drupal_set_title(t('Tell @recipient what you need help with', array('@recipient' => $recipients_plain)));
          if(isset($url_vals['group'])) {
            $form['subject']['#default_value'] = $user->name ." needs help with " .$url_vals['group'];
            $form['subject']['#type'] = 'hidden';
            $form_state['scheme_name'] = $url_vals['group'];
          }
        }else{
          drupal_set_title(t('Tell @recipient what '.$url_vals['type'] .' you can provide', array('@recipient' => $recipients_plain)));
          if(isset($url_vals['group'])) {
            $form['subject']['#default_value'] = $user->name ." has ".$url_vals['type'] ." for " .$url_vals['group'];
            $form['subject']['#type'] = 'hidden';
            $form_state['scheme_name'] = $url_vals['group'];
          }
        }
        if(isset($url_vals['gid'])) {
          $form_state['gid'] = $url_vals['gid'];
        }
      }else{
        drupal_set_title(t('Write new message to @recipient', array('@recipient' => $recipients_plain)));
      }
    }
    // Convert the recipient field to a value type and force the default value.
    $form['recipient']['#type'] = 'value';
    $form['recipient']['#value'] = $form['recipient']['#default_value'];
  }
}

/**
 * Parse the url for a message type. We use this to change
 * the title of the private message page to the scheme leader.
 */
function asb_message_privatemsg_check_url() {
  $vals = array();
  $url_vals = array();
  // Get the current url
  $url = drupal_get_destination();
  // Explode the url to get added elements
  $url_parse = explode('?',$url['destination']);
  // Get additional values
  if(isset($url_parse[1])) {
    $vals = explode('&', $url_parse[1]);
  }
  if(isset($vals[0])) {
    if($vals[0] === 'skills=1') {
      $url_vals['type'] = 'skills';
    }elseif($vals[0] === 'supplies=1') {
      $url_vals['type'] = 'supplies';
    }elseif($vals[0] === 'facilitator=1') {
      $url_vals['type'] = 'facilitator';
    }else{
      $url_vals['type'] = '';
    }
  }else{
    $url_vals['type'] = '';
  }
  if(isset($vals[1])) {
    // Return the scheme id and title.
    $gid = explode('=',$vals[1]);
    $node = node_load($gid[1]);
    $url_vals['group'] = $node->title;
    $url_vals['gid'] = $gid[1];
  }
  return $url_vals;
}

/**
 * Custom validation handler for privatemsg form donation links.
 */

function asb_message_add_scheme_link_validate(&$form, &$form_state) {
  // Add a link to the scheme in the body of the message
  $addtext = $form_state['values']['body']['value'] ."\n\n" .'<p class="pm-scheme-addition"><a class="pm-scheme-link" href="/node/' .$form_state['gid'] .'">' .$form_state['scheme_name'] .'</a></p>';
  $form_state['input']['body']['value'] = $addtext;
  $form_state['values']['body']['value'] = $addtext;
  $form['body']['value']['#value'] = $addtext;
  $form_state['validate_built_message']->body = $addtext;
}

function asb_message_quicktabs_tabstyles() {
  $tabstyles_directory = drupal_get_path('module', 'asb_message') . '/tabstyles';
  $files = file_scan_directory($tabstyles_directory, '/\.css$/');
  $tabstyles = array();
  foreach ($files as $file) {
    // Skip RTL files.
    if (!strpos($file->name, '-rtl')) {
      $tabstyles[$file->uri] = drupal_ucfirst($file->name);
    }
  }
  return $tabstyles;
}
