<?php
/**
 * @file
 * Code for the ASB Utility module.
 */

/**
 * Implements hook_image_default_styles().
 */
function asb_util_image_default_styles() {
  $styles = array();

  // Exported image style: gbz_listing_thumb.
  $styles['asb_scheme_preview_thumb'] = array(
    'name' => 'asb_scheme_preview',
    'effects' => array(
      3 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 214,
          'height' => 123,
        ),
        'weight' => 1,
      ),
    ),
  );
  return $styles;

    $styles['asb_header_strip'] = array(
    'name' => 'asb_header_strip',
    'effects' => array(
      3 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 160,
          'height' => 114,
        ),
        'weight' => 1,
      ),
    ),
  );
  return $styles;
}

/**
 * Implements hook_menu().
 * displays as a tab our test pages at /kalatheme
 */
function asb_util_menu() {
  $items = array();

  $items['testpages/scheme'] = array(
    'title' => 'Scheme',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('scheme_layout_test_page'),
    'access arguments' => array('administer nodes'),
  );

  $items['testpages/collection'] = array(
    'title' => 'Home',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('home_layout_test_page'),
    'access arguments' => array('administer nodes'),
  );

  return $items;

}

/**
 * Implements hook_theme().
 */
function asb_util_theme() {
  $items = array();

  $items['scheme_layout_test_page'] = array(
    'template' => 'scheme-layout',
  );

  $items['home_test_page'] = array(
    'template' => 'home-layout',
  );

  return $items;
}

/**
 * Implements hook_menu_block_blocks().
 */
function asb_util_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'asb_util-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => '',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}




