<?php

function sn_node_insert($node) {
  // Add subscription messages
  $message = message_create('group_content');
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_og_ref->set($node->og_group_ref['und'][0]['target_id']);
  $wrapper->field_node_ref_with_og->set($node->nid);
  $options = array(
    'rendered fields' => array(
      'message_notify_email_subject' => 'field_rendered_og_subject',
      'message_notify_email_body' => 'field_rendered_og_body',
    ),
  );
  $subscribe_options = array(
    'subscribe message' => FALSE,
    'email message' => TRUE,
  );
  message_subscribe_send_message('node', $node, $message, array('email' => $options), $subscribe_options);
}
